import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import ThemeContextProvider from "@/config/theme/ThemeProvider";
import "@/app/globals.css";
import React, { Suspense } from "react";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <ThemeContextProvider>
            <Suspense fallback={<div>Loading...</div>}>{children}</Suspense>
            <ToastContainer position="top-center" />
          </ThemeContextProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
